### ISSUE TITLE
element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by lzr-thierry** [pproctor182/radiation_ppo#1]
![image](https://user-images.githubusercontent.com/73570458/159617260-d08e3766-8b0d-4ffe-b309-61fe1657b65f.png)

when I tried to run ppo.py, I found that the pred model did not calculate grads...

**Comment by peproctor** [comment]
Thanks for discovering this! It seemed to be an issue with the latest PyTorch version. I have updated the PyTorch version in the requirements.yml to be 1.8 and the issue is resolved. You will have to reinstall the package. The root cause of the issue is that the gradients for the losses are dropped when assigning the loss to the loss array in the latest PyTorch (this does not happen in PyTorch 1.8).

**Comment by lzr-thierry** [comment]
> Thanks for discovering this! It seemed to be an issue with the latest PyTorch version. I have updated the PyTorch version in the requirements.yml to be 1.8 and the issue is resolved. You will have to reinstall the package. The root cause of the issue is that the gradients for the losses are dropped when assigning the loss to the loss array in the latest PyTorch (this does not happen in PyTorch 1.8).

Thank you for your indication, it can run successfully.

**Comment by ConnorBaker** [comment]
For what it's worth, it's fixed in my fork: https://github.com/ConnorBaker/radiation_ppo/commit/6debd3ee1e3cca79b7f60d2bb7b729aa50372d8a

**Comment by peproctor** [comment]
Nice, a simple fix! Looks like you are making great improvements to the code structure/organization in your fork
